---
- name: Yum update
  yum:
    name: '*'
    state: latest

- name: Install yum packages
  yum:
    name:
      - java-1.8.0-openjdk
      - unzip
      - wget
      - epel-release
      - libvirt
      - qemu-kvm
      - virt-install
      - virt-top
      - libguestfs-tools
      - bridge-utils
      - git
      - vim
      - docker
      - conntrack

- name: Download Minikube
  get_url:
    url: https://storage.googleapis.com/minikube/releases/latest/minikube-latest.x86_64.rpm
    dest: /home/minikube.rpm

- name: Install Minikube
  yum:
    name: /home/minikube.rpm
    state: present

