---
- name: Upgrade all packages
  yum:
    name: '*'
    state: latest

- name: Install a list of packages
  yum:
    name:
      - java-1.8.0-openjdk
      - unzip
      - wget
      - epel-release
      - libvirt
      - qemu-kvm
      - virt-install
      - virt-top
      - libguestfs-tools
      - bridge-utils
      - git
      - vim

- name: Enable service libvirtd
  systemd:
    name: libvirtd
    enabled: yes
    state: started

- name: Add centos user to group libvirt
  user:
    name: centos
    comment: CentOS
    group: libvirt

- name: config change sock_group - libvirt
  lineinfile:
    path: /etc/libvirt/libvirtd.conf
    regexp: '^unix_sock_group='
    line: unix_sock_group = "libvirt"
  register: sock_group

- name: config change sock_rw_perms - libvirt
  lineinfile:
    path: /etc/libvirt/libvirtd.conf
    regexp: '^sock_rw_perms='
    line: unix_sock_rw_perms = "0770"
  register: sock_rw_perms

- name: Restart libvirt service
  debug:
    msg: Restarting libvirt service
  notify:
    - "restart libvirt service"
  when: sock_group is succeeded and sock_rw_perms is succeeded

- name: Download Minikube
  get_url:
    url: https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
    dest: /usr/local/bin/minikube

- name: Changing perm of "/usr/local/bin/minikube", adding "+x"
  file: dest=/usr/local/bin/minikube mode=a+x

- name: Enable service minikube
  shell: >
    /usr/local/bin/minikube start
