---
- name: Install yum packages
  yum:
    name:
      - java-1.8.0-openjdk
      - unzip
      - docker

- name: Prepare Jenkins repo
  get_url:
    url: https://pkg.jenkins.io/redhat-stable/jenkins.repo
    dest: /etc/yum.repos.d/jenkins.repo

- name: Import Jenkins Key
  rpm_key:
    state: present
    key: https://pkg.jenkins.io/redhat-stable/jenkins.io.key

- name: Install Jenkins
  yum:
    name: jenkins
    state: present

- name: Start and enable Jenkins
  systemd:
    name: jenkins
    state: started
    enabled: true

- name: Timeout for Jenkins to startup
  wait_for: timeout=30

- name: Download and unarchive Packer.
  unarchive:
    src: https://releases.hashicorp.com/packer/{{ packer_version }}/packer_{{ packer_version }}_linux_{{ packer_arch }}.zip
    dest: "{{ packer_bin_path }}"
    remote_src: true
    creates: "{{ packer_bin_path }}/packer"
    mode: 0755

- name: Add jenkins user to docker group
  user:
    name: "jenkins"
    groups: docker
    append: true

- name: Get init password Jenkins
  shell: cat /var/lib/jenkins/secrets/initialAdminPassword
  changed_when: false
  register: result

- name: Print init password Jenkins
  debug:
    var: result.stdout